### ISSUE TITLE
group___enumerations.html not found

### ISSUE THREAD

**Issue by gausie** [GHGibonus/Atom-boilua#3]
The scraper fails cause this file doesn't exist

**Comment by GHGibonus** [comment]
Saw that. I'll be working on it shortly.

**Comment by zekotraceur** [comment]
Same in here:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\The Binding of Isaac Rebirth\\tools\\LuaDocs\\group___enumerations.html'

Failure in Atom-boilua when i Rebuild BoI Api

**Comment by GHGibonus** [comment]
Should be fixed with version 1.4.2 Reopen a new issue if you still encounter bugs.

If you are curious, it seems like Nicalis updated their version of doxygen and now the enum file ``group___enumerations.html`` became ``group__enums.html``
